title: "Moebius — TryHackMe"
description: "Professional web exploitation and container security case study."

theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - docs
